#!/usr/bin/env python3
"""Append-only AI audit logger for HW06.

Creates immutable interaction records and appends later human-review addenda.
No execution evidence is generated by this script.
"""

from __future__ import annotations

import argparse
import re
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

TZ = ZoneInfo("Asia/Ho_Chi_Minh")
VALID_CONTRIBUTIONS = {
    "AI-GENERATED",
    "AI-ASSISTED",
    "HUMAN-CREATED",
    "EXECUTION-EVIDENCE",
}
VALID_DECISIONS = {"ACCEPT", "MODIFY", "REJECT"}


def project_root() -> Path:
    return Path(__file__).resolve().parents[3]


def audit_paths() -> tuple[Path, Path]:
    root = project_root()
    audit_dir = root / "ai-audit"
    interactions_dir = audit_dir / "interactions"
    audit_dir.mkdir(parents=True, exist_ok=True)
    interactions_dir.mkdir(parents=True, exist_ok=True)
    return audit_dir, interactions_dir


def ensure_log(log_path: Path) -> None:
    if log_path.exists():
        return
    log_path.write_text(
        "# HW06 AI Audit Log\n\n"
        "> Append-only index of real AI interactions used in this homework.\n\n"
        "| ID | Date/Time | Tool | Stage | API | Contribution | Review | File |\n"
        "|---|---|---|---|---|---|---|---|\n",
        encoding="utf-8",
    )


def next_id(interactions_dir: Path) -> str:
    highest = 0
    for path in interactions_dir.glob("AI-*.md"):
        match = re.fullmatch(r"AI-(\d+)\.md", path.name)
        if match:
            highest = max(highest, int(match.group(1)))
    return f"AI-{highest + 1:03d}"


def read_value(inline: str | None, file_path: str | None, field: str) -> str:
    if inline is not None and file_path is not None:
        raise SystemExit(f"Use either --{field} or --{field}-file, not both.")
    if file_path is not None:
        return Path(file_path).read_text(encoding="utf-8").rstrip()
    if inline is not None:
        return inline.rstrip()
    raise SystemExit(f"Missing --{field} or --{field}-file.")


def append_log_row(
    log_path: Path,
    interaction_id: str,
    timestamp: datetime,
    tool: str,
    stage: str,
    api: str,
    contribution: str,
    review: str,
    filename: str,
) -> None:
    safe = lambda value: value.replace("|", "\\|").replace("\n", " ")
    row = (
        f"| {interaction_id} | {timestamp.isoformat(timespec='seconds')} | "
        f"{safe(tool)} | {safe(stage)} | {safe(api)} | {safe(contribution)} | "
        f"{review} | `interactions/{filename}` |\n"
    )
    with log_path.open("a", encoding="utf-8") as handle:
        handle.write(row)


def cmd_record(args: argparse.Namespace) -> None:
    audit_dir, interactions_dir = audit_paths()
    log_path = audit_dir / "audit-log.md"
    ensure_log(log_path)

    if args.contribution not in VALID_CONTRIBUTIONS:
        raise SystemExit(
            "Invalid contribution. Use one of: " + ", ".join(sorted(VALID_CONTRIBUTIONS))
        )

    prompt = read_value(args.prompt, args.prompt_file, "prompt")
    output = read_value(args.output, args.output_file, "output")
    interaction_id = next_id(interactions_dir)
    now = datetime.now(TZ)
    filename = f"{interaction_id}.md"
    path = interactions_dir / filename

    artifacts = args.artifact or []
    artifact_block = "\n".join(f"- `{item}`" for item in artifacts) or "- None recorded"

    content = f"""# Interaction {interaction_id}

- Tool: {args.tool}
- Date: {now.date().isoformat()}
- Time: {now.strftime('%H:%M:%S %z')}
- Stage: {args.stage}
- API: {args.api}
- Contribution: {args.contribution}

## Prompt

{prompt}

## AI Output

{output}

## Artifacts Affected

{artifact_block}

## Human Review

- Decision: PENDING
- Reason:
- Changes made:

## Final Result

Pending human review.
"""
    path.write_text(content, encoding="utf-8")
    append_log_row(
        log_path,
        interaction_id,
        now,
        args.tool,
        args.stage,
        args.api,
        args.contribution,
        "PENDING",
        filename,
    )
    print(path.relative_to(project_root()))


def cmd_review(args: argparse.Namespace) -> None:
    if args.decision not in VALID_DECISIONS:
        raise SystemExit("Decision must be ACCEPT, MODIFY, or REJECT.")
    if args.decision in {"MODIFY", "REJECT"} and not args.reason.strip():
        raise SystemExit(f"--reason is required for {args.decision}.")

    audit_dir, interactions_dir = audit_paths()
    path = interactions_dir / f"{args.id}.md"
    if not path.exists():
        raise SystemExit(f"Interaction not found: {args.id}")

    now = datetime.now(TZ)
    addendum = f"""

---

## Human Review Addendum — {now.isoformat(timespec='seconds')}

- Decision: {args.decision}
- Reason: {args.reason.strip() or 'No correction required.'}
- Changes made: {args.changes.strip() or 'None.'}

### Final Result

{args.final_result.strip()}
"""
    with path.open("a", encoding="utf-8") as handle:
        handle.write(addendum)

    review_log = audit_dir / "review-log.md"
    if not review_log.exists():
        review_log.write_text(
            "# HW06 AI Human Review Log\n\n"
            "| Date/Time | Interaction | Decision | Reason |\n"
            "|---|---|---|---|\n",
            encoding="utf-8",
        )
    safe_reason = args.reason.replace("|", "\\|").replace("\n", " ") or "No correction required."
    with review_log.open("a", encoding="utf-8") as handle:
        handle.write(
            f"| {now.isoformat(timespec='seconds')} | {args.id} | {args.decision} | {safe_reason} |\n"
        )
    print(path.relative_to(project_root()))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="HW06 append-only AI audit logger")
    sub = parser.add_subparsers(dest="command", required=True)

    record = sub.add_parser("record", help="Record a new AI interaction")
    record.add_argument("--tool", required=True)
    record.add_argument("--stage", required=True)
    record.add_argument("--api", default="N/A")
    record.add_argument("--contribution", required=True)
    record.add_argument("--prompt")
    record.add_argument("--prompt-file")
    record.add_argument("--output")
    record.add_argument("--output-file")
    record.add_argument("--artifact", action="append")
    record.set_defaults(func=cmd_record)

    review = sub.add_parser("review", help="Append a human review to an interaction")
    review.add_argument("--id", required=True)
    review.add_argument("--decision", required=True)
    review.add_argument("--reason", default="")
    review.add_argument("--changes", default="")
    review.add_argument("--final-result", required=True)
    review.set_defaults(func=cmd_review)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
